### ISSUE TITLE
Test output not showing 

### ISSUE THREAD

**Issue by benliddicott** [Microsoft/vscode-java-test#344]
Ouput pane does not show test output, seems to be happening since version 0.10.0 and/or the latest VSCode update, running in conjunction with the Microsoft Java Extension Pack 0.4.0.

* `Java: Show test output` does not work. 
    It selects the Output pane and selects "Test Output" in the dropdown, but no test output is visible. 

* `Java: Open Log` works and shows that the test output has appeared in the log

* This is reproducible from a Maven project built using the maven archetype-quickstart-jdk8 archetype.

**Comment by lwl19** [comment]
The same issue, test output panel is not working.

**Comment by IMEVER** [comment]
The same issue with version 1.27 and 1.28

**Comment by jdneo** [comment]
@benliddicott @lwl19 @IMEVER 

I found it very wried because if I disable the Maven extension, the output will just be fine. But if the Maven extension is enabled, the test output cannot be shown in the output channel.

Could you please have a try and let me know if it is just the same as what I said on your side?

**Comment by IMEVER** [comment]
@jdneo Yes, it works. When disable maven extension from workspace, reload vscode, run test, I can see test output right there.

**Comment by jdneo** [comment]
Hmm, Don't know who to blame for now. 😵 Let me investigate.

**Comment by cpdupuis** [comment]
I do see the test output when I click on the red X for a failed test in the editor pane (at least the assertion message and stack trace) when I use junit 4.12. When I use org.junit.Jupiter 5.3.1 and org.junit.platform 1.3.1, no output is shown at all when I click on the red X.

**Comment by AzureLithium** [comment]
> I do see the test output when I click on the red X for a failed test in the editor pane (at least the assertion message and stack trace) when I use junit 4.12. When I use org.junit.Jupiter 5.3.1 and org.junit.platform 1.3.1, no output is shown at all when I click on the red X.

I'm using org.junit.Jupiter 5.3.1 and org.junit.platform 1.3.1 and I can see the test output in the "Test Output" window whether the test passes or fails, doesn't matter, but that is if I have disabled the "Maven for Java" extension just as @jdneo said. If I don't disable that extension, "Test Output" window is always blank.

Definitely a bad interaction between these two extensions.

**Comment by xiaoxiaobingguai** [comment]
I have the same problem。How to resolve？

**Comment by myguddy** [comment]
Suggestion !

After disable maven I can see test logs in vscode output panel.

However, there are bunch of logs mixing of log from junit and user std output.
I am not sure of inside architecture of this extension( I love this thanks).

Why don't we separate the log data into junit log and std output from java code, System.out.print ?
So programmer can check test result quickly.

Thanks for your work done so far.

**Comment by jdneo** [comment]
@myguddy That's a good suggestion. Adding a tracking issue here: https://github.com/Microsoft/vscode-java-test/issues/358

**Comment by jdneo** [comment]
This should be fixed in `0.11.0`

**Comment by hgodoy** [comment]
I still have this problem, not output showing on debug console
vscode version : 1.34.0
maven plugin version: 0.17.0

**Comment by spark889** [comment]
Command palette:
java: open Test Runner log

**Comment by zygimantus** [comment]
I don't think this is fixed.

**Comment by flowt-au** [comment]
vsCode v1.51.1
Installed latest  Java Extension Pack  and disabled Maven for Java.
Without using JUnit I can "Run" my class and get the `System.out.println()` in the Java Process Console. Good.
If I run a test of the same class using JUnit "Run test" I see the test results "Passed" in the Java Test Report pane but nothing appears in the Java Process Console. :-( 
It would be great if that was working. Am I missing something? (Pretty new to all this)
Thanks,
Murray

**Comment by jdneo** [comment]
@flowt-au I cannot repro this on my machine. Please make sure you are checking the `DEBUG CONSOLE` for your program output (not the `OUTPUT` panel).

![image](https://user-images.githubusercontent.com/6193897/99923616-80c6d200-2d71-11eb-8f3f-5852f5961083.png)

Could you share more details for this? If you don't mind, please share a sample project and the expected output in the debug console. I can take a look.

**Comment by flowt-au** [comment]
Thanks. Sorry, my confusion as I am learning.
When running a java class (not in JUnit) the System.out.println(); shows in the **Terminal Java Process Console**.
When running in JUnit, the System.out.println(); shows in the **Debug Console**.  As I was flipping between the two it did not display the debug console and I was expecting it to appear in the Terminal. 
Apologies again and thanks for following up.
Go well,
Murray

**Comment by jdneo** [comment]
@flowt-au I see. Thank you for your feedback. Actually I think this is a valid request since other users may encounter the same problem as well. I'll consider if it is possible to execute the test in terminal as well.

**Comment by flowt-au** [comment]
Thanks! :-)
